name: CI

on:
  push:
    # branches:
    #   - main
  pull_request:
    # branches:
    #   - main

jobs:
  publish:
    name: Build and publish package
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build and publish package
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          export VERSION=$(cat VERSION)
          sed -e 's#{VERSION}#'"${VERSION}"'#g' pyproject_template.toml > pyproject.toml
          python -m poetry build
          poetry publish --username __token__ --password "$PYPI_API_TOKEN"
